<a href="https://colab.research.google.com/github/sai-bharghav/pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

# Tensors
* A Torch. Tensor is a multidimensional matrix containing elements of a single data type
* Similar to NumPyArrays, but can work better on GPU's
* default data type is float32


# LISTS

In [3]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
multi = [[1,2,3,4,5],[6,7,8,9,0]]
multi

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]

# Numpy Arrays

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.89390894, 0.57469366, 0.07711974, 0.4470976 ],
       [0.26610929, 0.5414154 , 0.49270836, 0.15262686],
       [0.14375521, 0.06757198, 0.91022359, 0.23961516]])

In [6]:
np1.dtype

dtype('float64')

# Tensors

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.4128, -0.0810, -1.2095,  1.2265],
        [ 0.0048,  0.5294,  1.1759, -1.8616],
        [-0.8125,  2.1117, -0.0555,  0.5066]])

In [8]:
tensor_2d.dtype

torch.float32

In [11]:
tensor_3d = torch.zeros(2,3,4)

In [12]:
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
# Create tesnor out of numpy array
my_tensor= torch.tensor(np1)

In [16]:
my_tensor

tensor([[0.8939, 0.5747, 0.0771, 0.4471],
        [0.2661, 0.5414, 0.4927, 0.1526],
        [0.1438, 0.0676, 0.9102, 0.2396]], dtype=torch.float64)