<a href="https://colab.research.google.com/github/sai-bharghav/pytorch/blob/main/TensorMath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

# Addition

In [3]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# Addition longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

# Subtraction

In [5]:
tensor_a-tensor_b

tensor([-4, -4, -4, -4])

In [7]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

#Multiplication

In [8]:
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

# Divison

In [11]:
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

#Remainder

In [13]:
tensor_b% tensor_a

tensor([0, 0, 1, 0])

In [16]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

# Exponents

In [17]:
tensor_a**tensor_b

tensor([    1,    64,  2187, 65536])

In [18]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

# Reassignment

In [19]:
#tensor_a=tensor_a+tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [20]:
tensor_a

tensor([ 6,  8, 10, 12])